server:
  port: 8080
  servlet:
    context-path: /osf
    session:
      timeout: 200m
    encoding:
      enabled: true
      charset: UTF-8
      force: true
    jsp:
      init-parameters:
        development: true
  error:
    whitelabel:
      enabled: false
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 20

spring:
  application:
    name: ace
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/osf?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: mysql-pool
      max-lifetime: 600000
      connection-timeout: 30000
      connection-test-query: select 1
      validation-timeout: 30000
      transaction-isolation: TRANSACTION_READ_COMMITTED
      readOnly: false
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 10
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
  mail:
    default-encoding: utf-8
    host: smtp.example.com
    username: your-email@example.com
    password: your-password
    port: 587
    protocol: smtp
  messages:
    encoding: UTF-8
  mvc:
    converters:
      preferred-json-mapper: fastjson
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /assets/**,/static/**
    view:
      prefix: /jsp/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  web:
    resources:
      static-locations: classpath:/assets/,classpath:/static/,classpath:/html/
  devtools:
    restart:
      enabled: false
      exclude: static/**,public/**,site/**,cache/**,head/**

# mybatis
mybatis:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
  type-aliases-package: com.fit.entity
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    web: info
  file:
    path: ./target/log
debug: false

web_path: 'http://127.0.0.1:8080/'
activate_context: '/account/activation/'
img_base_url: 'http\://7xkkim.com1.z0.glb.clouddn.com/'
post_cover_thumbnail: '?imageView2/2/w/500'
album_thumbnail: '?imageView2/1/w/200/h/200'